# This file was generated by GoReleaser. DO NOT EDIT.
class CostCli < Formula
  desc "CLI for analyzing, visualizing and forecasting cost usages."
  homepage "https://dobbeltk.dk/"
  version "0.9.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/pdsorensen/cost-cli/releases/download/v0.9.3/cost-cli_0.9.3_Darwin_x86_64.tar.gz"
    sha256 "7181427062d9b710a2e8414c17d19c8650f7d7a65bd57a8da8b4ae29b5fa5214"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/pdsorensen/cost-cli/releases/download/v0.9.3/cost-cli_0.9.3_Linux_x86_64.tar.gz"
      sha256 "c4a56a7bbea6bd2f48ca5b3dcf5d86e130cf189010ce81b3feeea1ded85253ca"
    end
  end
  
  depends_on "git"
  depends_on "zsh" => :optional
  
  conflicts_with "svn"
  conflicts_with "bash"

  def install
    bin.install "cost-cli"
  end
end
