# This file was generated by GoReleaser. DO NOT EDIT.
class CostCli < Formula
  desc "Software to create fast and easy drum rolls."
  homepage "https://example.com/"
  version "0.9.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.9.1/cost-cli_0.9.1_Darwin_x86_64.tar.gz"
    sha256 "516a0de9af77997a947a5da1ec74f9f9c0ebe9d01778c2aff362918918d8f0f5"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.9.1/cost-cli_0.9.1_Linux_x86_64.tar.gz"
      sha256 "dcf1e82a245f8b70eefad941aa2a80825435c4c8ae526a636d4223c1f6adadba"
    end
  end
  
  depends_on "git"
  depends_on "zsh" => :optional
  
  conflicts_with "svn"
  conflicts_with "bash"

  def install
    bin.install "cost-cli"
    ...
  end
end
